### ISSUE TITLE
无法搜索名为 xls_story_xxx  的文件夹

### ISSUE THREAD

**Issue by yanghuan** [elroy93/searchXlsGui#1]
发现一个很奇怪的问题，无法搜索到名为 xls_story_xxx  的文件夹下的文件，当文件夹名字是  xls_story_xxx 的时候，感觉返回了空文件列表，无法搜索到任何文本

**Comment by e1roy** [comment]
已更新. 
---  
原因是在我们的项目中 xls_story_是废弃文件夹🤦‍♂️
